### ISSUE TITLE
Get IP address 

### ISSUE THREAD

**Issue by kanuva** [stnkl/ESPEssentials#12]
I can't seem to figure out how to get the local IP address of the ESP32 once it's connected to any WIFI. My plan is to show this IP address on a small display once it's connected so I don't need a PC to find the IP address from the serial monitor. Can you help me please?

**Comment by wilmouths** [comment]
Hello,
You need to include ``WiFi.h`` and call ``WiFi.localIP()``;
```cpp
#include <WiFi.h>

void setup() {}

void loop() {
  Serial.println(WiFi.localIP());
}
```

**Comment by kanuva** [comment]
Thanks! I assumed that I didn't need to include Wifi.h since ESPEssentials.h is using EEWifi.h which in its turn is using Wifimanger.h which is using Wifi.h.

Stupid of me that I never just tried to incluse wifi.h since I assumed it would cause problems because I thought it's allready being used.
