### ISSUE TITLE
http://192.168.43.216/reboot   Oops, file not found!

### ISSUE THREAD

**Issue by huster-songtao** [stnkl/ESPEssentials#13]
http://[192.168.43.216/list?dir=/](http://192.168.43.216/list?dir=/)

response 200:
[]

![image](https://github.com/srwi/ESPEssentials/assets/94954133/3f186efe-8acf-45c6-83f9-8b055d8e0027)

but I got http://[192.168.43.216/reboot](http://192.168.43.216/reboot)
![image](https://github.com/srwi/ESPEssentials/assets/94954133/8546934a-207c-45e0-9df4-20c9c4cff237)

why 404?

**Comment by srwi** [comment]
The bug has been fixed and will be released soon. Thanks for bringing it to my attention.
