### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by StefanL38** [stnkl/ESPEssentials#6]
I flashed your example-code into an ESP8266 
The serial monitor shows
`*wm:[1] AutoConnect 
*wm:[2] Connecting as wifi client... 
*wm:[2] setSTAConfig static ip not set, skipping 
*wm:[1] Connecting to SAVED AP: FRITZ!Box 7490
*wm:[1] connectTimeout not set, ESP waitForConnectResult... 
*wm:[2] Connection result: WL_CONNECTED
*wm:[1] AutoConnect: SUCCESS 
*wm:[2] Connected in 946 ms
*wm:[1] STA IP Address: 192.168.178.96
[OTA] OTA started
[Storage] Couldn't find file at '/'.
[Storage] Couldn't find file at '/favicon.ico'.
[Storage] Couldn't find file at '/'.
[Storage] Couldn't find file at '/'.
`
If I try to connect to the ESP8266 with the given IP all I get is a
Oops, file not found!

Well beeing so much "essential"  that just connecting to WiFi works is a little too less

best regards Stefan

**Comment by srwi** [comment]
Hi @StefanL38, you would have to upload some html files to be able to load them from the ESP8266 filesystem. You can do that by opening `http://<device-ip>/edit`. Please have a look again at the [Webserver section](https://github.com/stnkl/ESPEssentials#webserver) in the readme.

You probably want to upload the `index.htm` file.
