### ISSUE TITLE
Error finding LittleFS when compiling with ESP32

### ISSUE THREAD

**Issue by swilson86** [stnkl/ESPEssentials#7]
There seems to be a bug when compiling everything with Arduino IDE 1.8.19 "right out of the box" using an ESP32. I get the following error:

ResolveLibrary(LittleFS.h)o\Sketches\libraries\ESPEssentials\src\EEWebServer.cpp:21:23: fatal error: LittleFS.h: No such file or directory

To try and resolve I added the LittleFS_esp32 library by lorol version 1.06 but it throws even more errors (incompatability). Thus that library cannot be the correct one for the ESP32. I next tried to compiler with an ESP8266 chip and that worked ok as I can see the compiler picked up the all the correct libraries for the ESP8266 (including the LittleFS.h version created for the ESP8266).

**Comment by srwi** [comment]
Hi @swilson86. You will need at least core version 2.0.0 for the ESP32. You can update it in the board manager of your Arduino IDE.

**Comment by swilson86** [comment]
Thanks stnkl !! That was the solution... It now compiles and uploads to my ESP32 dev board. 

To those reading this in the future,... put this line in your Arduino IDE in File > Preferences > Addition Boards Manager URL's

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
